#!/bin/bash

# git hook to run a command after `git pull` if a specified file was changed

changed_files="$(git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD)"

check_run() {
	echo "$changed_files" | grep --quiet "$1" && eval "$2"
}


check_run buildout.cfg "echo *****************Buildout config file changed. You might have to Run bin/buildout"
check_run setup.py "echo *****************setup.py file changed. You might have to Run bin/buildout"